name: CI Pipeline (Python)

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Executar script principal do projeto
        run: python main.py
